# Generated by Django 4.0.4 on 2022-05-28 22:01

import base.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z,0-9]*$', 'Seules les lettres sont autorisées.')])),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, default='NULL.png', upload_to=base.models.path_image)),
                ('stadium', models.CharField(blank=True, max_length=30)),
                ('rating', models.PositiveIntegerField(blank=True, default=0)),
                ('website', models.URLField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('family_name', models.CharField(max_length=15)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='_NULL.png', upload_to=base.models.path_imag_p)),
                ('club', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach', to='base.club')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Seules les lettres sont autorisées.')])),
                ('name', models.CharField(max_length=30)),
                ('flag', models.ImageField(blank=True, default='__NULL.png', upload_to=base.models.path_image)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Seules les lettres sont autorisées.')])),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, default='NULL.png', upload_to=base.models.path_image)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('confederation', models.CharField(choices=[('UEFA', 'UEFA'), ('CAF', 'CAF'), ('AFCON', 'AFCON')], max_length=30)),
                ('type', models.CharField(choices=[('Ligue Nationale', 'Ligue Nationale'), ('Coupe Nationale', 'Coupe Nationale'), ('Coupe Continentale', 'Coupe Continentale'), ('Coupe Internationale', 'Coupe Internationale')], max_length=30)),
                ('clubs', models.ManyToManyField(related_name='leagues', to='base.club')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues', to='base.country')),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_Goals_H', models.PositiveIntegerField(blank=True, default=0)),
                ('n_Goals_A', models.PositiveIntegerField(blank=True, default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('Team_A', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='base.club')),
                ('Team_H', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs', to='base.club')),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.league')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('family_name', models.CharField(max_length=15)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(choices=[('Gardien de but', 'Gardien de but'), ('Défenseur', 'Défenseur'), ('Milieu de terrain', 'Milieu de terrain'), ('Attaquant', 'Attaquant')], max_length=20)),
                ('number', models.PositiveIntegerField(null=True)),
                ('photo', models.ImageField(blank=True, default='_NULL.png', upload_to=base.models.path_imag_p)),
                ('Club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='base.club')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='base.country')),
            ],
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='admins/')),
            ],
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
        migrations.AddField(
            model_name='coach',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach', to='base.country'),
        ),
        migrations.AddField(
            model_name='club',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='base.country'),
        ),
    ]
