# Generated by Django 4.0.4 on 2022-05-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_club_coach_country_league_match_player_testdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
    ]
