# Generated by Django 4.0.4 on 2022-06-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_club_coach_country_league_match_player_testdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='goals_a',
            new_name='n_goals_a',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='goals_h',
            new_name='n_goals_h',
        ),
    ]
