# Generated by Django 4.0.4 on 2022-05-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_clubs_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, upload_to='clubs/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
