# Generated by Django 4.0.4 on 2022-05-19 23:18

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_club_logo_alter_club_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, upload_to=base.models.path_image),
        ),
    ]
