# Generated by Django 4.0.4 on 2022-05-20 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Only uppercase letters and underscores allowed.')]),
        ),
    ]
