# Generated by Django 4.0.4 on 2022-05-20 12:09

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_club_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z,a-z]*$', 'Seules les lettres sont autorisées.')])),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, upload_to=base.models.path_image)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('country', models.CharField(choices=[('EN', 'Angleterre'), ('MA', 'Maroc'), ('FR', 'France')], max_length=5)),
                ('confederation', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z,a-z]*$', 'Seules les lettres sont autorisées.')]),
        ),
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.CharField(choices=[('EN', 'Angleterre'), ('MA', 'Maroc'), ('FR', 'France')], max_length=5),
        ),
    ]
