# Generated by Django 4.0.4 on 2022-05-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_league_alter_club_code_alter_club_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.CharField(blank=True, choices=[('EN', 'Angleterre'), ('MA', 'Maroc'), ('FR', 'France')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='type',
            field=models.CharField(choices=[('LN', 'Ligue Nationale'), ('CN', 'Coupe Nationale'), ('CC', 'Coupe Continentale'), ('CI', 'Coupe Internationale')], max_length=30),
        ),
    ]
