# Generated by Django 4.0.4 on 2022-05-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_club_country_alter_league_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='confederation',
            field=models.CharField(choices=[('UEFA', 'UEFA'), ('CAF', 'CAF'), ('AFCON', 'AFCON')], max_length=30),
        ),
    ]
