# Generated by Django 4.0.4 on 2022-05-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_league_confederation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='type',
            field=models.CharField(choices=[('National League', 'Ligue Nationale'), ('National Cup', 'Coupe Nationale'), ('Continental Cup', 'Coupe Continentale'), ('Continental Cup', 'Coupe Internationale')], max_length=30),
        ),
    ]
