# Generated by Django 4.0.4 on 2022-05-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_league_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.CharField(blank=True, choices=[('gb-eng', 'Angleterre'), ('ma', 'Maroc'), ('fr', 'France')], max_length=10),
        ),
        migrations.AlterField(
            model_name='league',
            name='country',
            field=models.CharField(choices=[('gb-eng', 'Angleterre'), ('ma', 'Maroc'), ('fr', 'France')], max_length=10),
        ),
    ]
