# Generated by Django 4.0.4 on 2022-05-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('code', models.SlugField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='clubs/')),
                ('website', models.URLField(max_length=100)),
                ('country', models.CharField(choices=[('MA', 'Maroc'), ('FR', 'France'), ('EN', 'Angleterre')], max_length=5)),
            ],
        ),
    ]
